### ISSUE TITLE
怎么判断是否连接成功？

### ISSUE THREAD

**Issue by zoujiaqing** [deepseeksss/tokio_kcp#43]
调用 connect 方法直接返回了 stream 对象，就算没网也会返回 stream ，不科学。

**Comment by zoujiaqing** [comment]
怎么判断一下是否真的建立了连接，得自己发送一个请求并返回？

**Comment by zonyitoo** [comment]
Yes, it is. KCP is based on UDP, which doesn't actually has a `CONNECT` process.
